# Generated by Django 3.1 on 2020-09-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120)),
                ('phone_no', models.CharField(max_length=20)),
                ('mess', models.CharField(max_length=250)),
            ],
        ),
    ]
