# Generated by Django 3.1 on 2020-09-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mess',
            new_name='message',
        ),
    ]
